# Generated by Django 4.2.7 on 2023-12-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_app", "0002_remove_product_id_alter_product_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.IntegerField(primary_key=True, serialize=False)),
                ("order_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Order_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant_app.order",
                    ),
                ),
                (
                    "product_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant_app.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("order_id", "product_name")},
            },
        ),
    ]
