# Generated by Django 4.2.7 on 2023-12-12 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_app", "0003_order_order_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order_product",
            old_name="order_id",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="order_product",
            old_name="product_name",
            new_name="product",
        ),
        migrations.AlterUniqueTogether(
            name="order_product",
            unique_together={("order", "product")},
        ),
    ]
