# Generated by Django 4.2.7 on 2023-12-12 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_app", "0004_rename_order_id_order_product_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_id"]},
        ),
    ]
